name: Deploy to Heroku and run tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: create env file
        run: |
          touch .env
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
          echo MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} >> .env
          echo SERVER_SECRET=${{ secrets.SERVER_SECRET }} >> .env
          echo NEO4J_URI=${{ secrets.NEO4J_URI }} >> .env
          echo NEO4J_USERNAME=${{ secrets.NEO4J_USERNAME }} >> .env
          echo NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }} >> .env
          echo NEO4J_DB_NAME=${{ secrets.NEO4J_DB_NAME }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
      - name: Run tests
        run: npm test
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "val-api"
          heroku_email: "borispouw@gmail.com"
